### ISSUE TITLE
NuGet packages cannot be restored

### ISSUE THREAD

**Issue by v-vasilev-synergy** [jsuarezruiz/forms-embedding-wpf#1]
There are six errors when trying to build the project from a clean clone:

It seems that some projects cannot be restored. Can you include them as packages in the solution?

**Comment by jsuarezruiz** [comment]
Initially, Nightly packages of Xamarin.Forms were used. If you do not have the Xamarin.Forms Nightly packages source added to Visual Studio, you get the errors you indicate.
I have updated the project with public packages as well as other changes (from PCL to .NET Standard).
